name: CI

on:
  push:
    paths:
      - '**/.php'
      - '**/.yml'
      - '**/.json'
      - '.env.*'
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Setup dev environment
        run: docker-compose exec -T dev-kit composer run dev
      - name: Postman tests
        run: docker-compose exec -T dev-kit postman collection run postman/ci-collection.json
